"""
Even Fibonacci numbers
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

sum = 2  # Initial even value
upper_bound = 4000000
fib_vals = [1, 2]  # Initial values
current_val = fib_vals[-1] + fib_vals[-2]

while current_val < upper_bound:
    if current_val % 2 == 0:
        print(current_val)
        sum += current_val
    fib_vals.append(current_val)
    current_val = fib_vals[-1] + fib_vals[-2]

print(sum)
